### PR TITLE
refactor: update models

### PR DESCRIPTION
**Pull request by nickhsine**
BREAKING CHANGE: remove index from models and delete unused index

### CODE REVIEW

**Comment by babygoat** [comment]
After a second thought, it seemed to me that the problematic index creation resulted from the default mongoose schema creation. Thus, we can keep the index signature in the model layer and only disable the index creation in production environment, which seemed more reasonable to me. Also, I would like to have the test items for further integration testing.

**Comment by nickhsine** [comment]
Updated.

**Comment by babygoat** [comment]
LGTM. We can have this change along with twreporter/keystone#152 for the staging testing. I have deployed the updated nginx for staging environment.

**Comment by babygoat** [comment]
Moreover, the cluster is resized to accommodate keystone on staging environment as well as the config for DNS are configured accordingly.

**Pull request merged**
