### PR TITLE
refactor: change session key to `keystone.sid`

### PR DESCRIPTION
**Pull request by babygoat**
This patch changes the session key to `keystone.sid` for better
identification.

### CODE REVIEW

**Comment by taylrj** [comment]
I suppose we will no longer have cookie in name 'this.sid' base on [L23](https://github.com/twreporter/keystone/blob/e06ce10e5af1e96872e1ccf42c0aa2f8d4d649e6/lib/core/initExpressSession.js#L23) in `initExpressSession`.

Do we need to update it to 'keystone.sid' as well ?

**Comment by babygoat** [comment]
I don't have a strong opinion here.  As for our usage, our dev environment will use the config generated from `build-config.js`

**Comment by taylrj** [comment]
LGTM

**Review by Aylie-Chou — APPROVED** [review]
LGTM

**Pull request merged**
